name = "subtls-wsproxy"
compatibility_date = "2023-09-11"
compatibility_flags = [ "no_web_socket_compression" ]
main = "worker.js"

[vars]
ADDRESS_REGEXP = "^[-.a-zA-Z0-9]+[.]neon[.]tech:5432$|^subtls[.]pages[.]dev:443$"
